require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require 'fileutils'
require 'json'
require 'pathname'

shell_dir = Pathname.new(ENV['LEGEND_SHELL_ROOT'] || File.expand_path("..", __dir__))
repo_root = shell_dir.parent
app_root = Pathname.new(ENV['LEGEND_APP_ROOT'] || shell_dir.to_s)
app_config_path = ENV['LEGEND_APP_CONFIG']
app_config = app_config_path && File.exist?(app_config_path) ? JSON.parse(File.read(app_config_path)) : {}
uses_diff_parser = app_config
    .fetch("activeNativePackages", [])
    .any? { |native_package| native_package["name"] == "@legend-apps/diff-parser" }
uses_expo_modules = ENV['LEGEND_USE_EXPO_MODULES'] != '0'
rn_macos_absolute_path = shell_dir.join("node_modules", "react-native-macos")
rn_macos_path = rn_macos_absolute_path.relative_path_from(Pathname.new(__dir__)).to_s
require "#{rn_macos_absolute_path}/scripts/react_native_pods.rb"

ENV['RCT_NEW_ARCH_ENABLED'] = "1";

prepare_react_native_project!

target 'legendapp-shell-macos' do
  platform :osx, '14.0'
  use_expo_modules! if uses_expo_modules
  pod 'LegendLibGit2', :podspec => repo_root.join("packages/libgit2/LegendLibGit2.podspec").to_s if uses_diff_parser

  config_command = [
    'npx',
    'expo-modules-autolinking',
    'react-native-config',
    '--json',
    '--platform',
    'ios'
  ]
  config = use_native_modules!(config_command)

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => rn_macos_path,
    :fabric_enabled => ENV['RCT_NEW_ARCH_ENABLED'] == '1',
    # An absolute path to your application root.
    :app_path => app_root.to_s
  )

  post_install do |installer|
    react_native_post_install(installer, rn_macos_path)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if target.name == 'fmt'
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++17'
        end
      end
    end

    if uses_diff_parser
      FileUtils.rm_rf(installer.sandbox.root + 'Headers/Public/LegendLibGit2')

      Dir[installer.sandbox.root + 'Target Support Files/**/*.xcconfig'].each do |xcconfig_path|
        xcconfig = File.read(xcconfig_path)
        xcconfig = xcconfig.gsub(' "${PODS_ROOT}/Headers/Public/LegendLibGit2"', '')
        xcconfig = xcconfig.gsub(' "-F${PODS_CONFIGURATION_BUILD_DIR}/LegendLibGit2"', '')
        xcconfig = xcconfig.gsub(' "${PODS_ROOT}/Headers/Public/LegendLibGit2/**"', '')
        File.write(xcconfig_path, xcconfig)
      end
    end
  end
end
